
sudo: required

services: docker

before_install:
  - docker build -f dea/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true dea/react-test npm test

after_success:
  - docker build dea/multi-client ./client
  - docker build dea/multi-nginx ./nginx
  - docker build dea/multi-server ./server
  - docker build dea/multi-worker ./worker
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push dea/multi-client
    - docker push dea/multi-nginx
    - docker push dea/multi-server
    - docker push dea/multi-worker
